github.com:
    users:
        KC-OU:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: KC-OU
